[package]
name = "azuran"
version = "0.1.0"
authors = ["officialcjunior <realc@protonmail.com>"]
edition = "2018"

[[bin]]
name = "azuran"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
